name: "Deploy"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: CutieDiscordBot
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '16.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: NPM Install
      run: npm install

    - name: Register Commands
      run: npm run deploy
      env:
        DISCORD_BOT_CLIENT_ID: '995996481783861299'
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CutieDiscordBot
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: CutieDiscordBot

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}